spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      type: com.alibaba.druid.pool.DruidDataSource
      
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    
mybatis:
  mapper-locations: classpath:com/mapper/**/*.xml
  
