spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      type: com.alibaba.druid.pool.DruidDataSource
      
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8

#Redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码
    password: 12345
    
    jedis:
      pool:
        #连接池最大连接数（使用负数表示没有限制）
        max-active: 200
        #连接池最大阻塞等待时间（使用负数表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 1000
    
    
    
    
#mybatis扫描xml文件   
mybatis:
  mapper-locations: classpath:com/mapper/**/*.xml



